### Delete a Todo by ID USER
DELETE http://localhost:8080/api/v1/todos/15
Accept: application/json
Authorization: Basic dGVzdDp0ZXN0

### Delete a Todo by ID ADMIN
DELETE http://localhost:8080/api/v1/todos/18
Accept: application/json
Authorization: Basic YWRtaW46YWRtaW4=
