### Update an existing Todo as ADMIN
PUT http://localhost:8080/api/v1/todos/1
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "title": "Updated Todo",
  "description": "This todo has been updated",
  "completed": true
}

### Update an existing Todo as USER
PUT http://localhost:8080/api/v1/todos/1
Content-Type: application/json
Authorization: Basic dXNlcjE6cGFzc3dvcmQ=

{
  "title": "Updated Todo",
  "description": "This todo has been updated",
  "completed": true
}

