### Register a new user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "John Doe4",
  "username": "johndoe4",
  "email": "johndoe4@example.com",
  "password": "password1234"
}
